'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AGM_Vote

    '''<summary>
    '''VotingTables control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VotingTables As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Ordinary_Resolutions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ordinary_Resolutions As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Special_Resolutions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Special_Resolutions As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Elections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Elections As Global.System.Web.UI.HtmlControls.HtmlTable
End Class
