'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CompetitionsEntryForm

    '''<summary>
    '''Season_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Season_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''Update_Progress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Update_Progress As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''Head_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Club_Selector_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Club_Selector_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Club_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Club_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Club_WIP_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Club_WIP_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CompetitionsPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompetitionsPanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Competitions_GridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Competitions_GridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Comment_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Comment_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Fee_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fee_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Show_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Show_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NonClub_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NonClub_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Entrants_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Entrants_CheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Entrants_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Entrants_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SortBy_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SortBy_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''SortBy_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SortBy_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Entrant2_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Entrant2_CheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Entrant2_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Entrant2_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''divHCapMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divHCapMsg As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''notQualified_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents notQualified_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Entrants_GridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Entrants_GridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SaveCompetition_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveCompetition_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''SaveCompetition_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveCompetition_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''privacyCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents privacyCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''submitEntryForm_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents submitEntryForm_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Submit_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Submit_Literal As Global.System.Web.UI.WebControls.Literal
End Class
