'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EntryForm

    '''<summary>
    '''Season_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Season_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Head_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ToolkitScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolkitScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''Update_Progress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Update_Progress As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''userHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userHiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ClubLoginIDHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClubLoginIDHiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''adminHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adminHiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''clubSaveButtonHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clubSaveButtonHiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''leagueIDHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents leagueIDHiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Club_Selector_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Club_Selector_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Club_UpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Club_UpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Acceptance_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Acceptance_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''AcceptanceCopy_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AcceptanceCopy_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Accept_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Accept_CheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Accept_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Accept_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Club_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Club_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Club_Fee_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Club_Fee_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Club_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Club_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Show_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Show_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Club_WIP_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Club_WIP_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''PayNotice2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PayNotice2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ClubDetails_Table control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClubDetails_Table As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Club_Name_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Club_Name_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Club_Addr1_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Club_Addr1_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Club_Contact_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Club_Contact_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Club_Addr2_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Club_Addr2_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Club_Telephone_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Club_Telephone_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Club_PostCode_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Club_PostCode_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Club_Mobile_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Club_Mobile_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Club_NoTables_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Club_NoTables_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Club_Email_Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Club_Email_Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Club_Save_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Club_Save_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Club_Status_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Club_Status_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Teams_UpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Teams_UpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Teams_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Teams_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Teams_GridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Teams_GridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''divConfirmDeleteTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divConfirmDeleteTeam As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DeleteTeam_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteTeam_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''DeleteTeam_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteTeam_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''KeepTeam_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents KeepTeam_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Teams_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Teams_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Team_Add_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team_Add_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Team_Fee_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team_Fee_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Team_League_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team_League_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Team_Letter_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team_Letter_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Team_ContactCaptain_Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team_ContactCaptain_Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Team_ContactCaptain_PlayerID_HiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team_ContactCaptain_PlayerID_HiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Team_Save_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team_Save_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Team_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''teamLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents teamLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Player_Find_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Player_Find_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Player_Error_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Player_Error_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Players_GridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Players_GridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''privacyCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents privacyCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''submitEntryForm_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents submitEntryForm_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''submitErrorMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents submitErrorMsg As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Player_Edit_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Player_Edit_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''AddEdit_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddEdit_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Player_Status_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Player_Status_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Player_Forename_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Player_Forename_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Player_Inits_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Player_Inits_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Player_Surname_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Player_Surname_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Player_Handicap_Text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Player_Handicap_Text As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Player_Tag_Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Player_Tag_Value As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''Player_Tag_Text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Player_Tag_Text As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Player_Over70_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Player_Over70_CheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Player_email_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Player_email_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Player_TelNo_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Player_TelNo_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Player_Submit_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Player_Submit_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Player_Cancel_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Player_Cancel_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Player_Similar_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Player_Similar_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Player_Similar_GridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Player_Similar_GridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Player_Similar_Add_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Player_Similar_Add_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Player_Transfer_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Player_Transfer_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Player_Transfer_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Player_Transfer_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AutoCompleteExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AutoCompleteExtender1 As Global.AjaxControlToolkit.AutoCompleteExtender

    '''<summary>
    '''Player_Transfer_GetByName_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Player_Transfer_GetByName_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Player_Transfer_Cancel_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Player_Transfer_Cancel_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Player_Add_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Player_Add_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Player_Transfer_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Player_Transfer_Literal As Global.System.Web.UI.WebControls.Literal
End Class
