'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EntryFormsDownload
    
    '''<summary>
    '''Chooser_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Chooser_Literal As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ChooserTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChooserTable As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''Type_RadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Type_RadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''Leagues_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Leagues_Panel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''DownloadOpen_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DownloadOpen_Button As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DownloadVets_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DownloadVets_Button As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DownloadBilliards_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DownloadBilliards_Button As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Competitions_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Competitions_Panel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''DownloadSnookerComps_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DownloadSnookerComps_Button As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DownLoadVetsComps_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DownLoadVetsComps_Button As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DownLoadBilliardsComps_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DownLoadBilliardsComps_Button As Global.System.Web.UI.WebControls.Button
End Class
