'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Fines1
    
    '''<summary>
    '''Owing_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Owing_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Export_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Export_Button As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Fines_GridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fines_GridView As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''Payments_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Payments_Panel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''PaymentsPanel_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaymentsPanel_Literal As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''Payments_GridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Payments_GridView As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''PaymentsClose_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaymentsClose_Button As Global.System.Web.UI.WebControls.Button
End Class
