'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class JuniorsComp2

    '''<summary>
    '''juniorContentLiteral1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents juniorContentLiteral1 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Table1_GridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table1_GridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Table2_GridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table2_GridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Table3_GridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table3_GridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Table4_GridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table4_GridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Results1_Gridview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Results1_Gridview As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Div2Head control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div2Head As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Results2_Gridview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Results2_Gridview As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Div3Head control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div3Head As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Results3_Gridview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Results3_Gridview As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Div4Head control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div4Head As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Results4_Gridview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Results4_Gridview As Global.System.Web.UI.WebControls.GridView
End Class
