'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LoginProfile

    '''<summary>
    '''League_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents League_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Section_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Section_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Club_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Club_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Team_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''FirstName_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FirstName_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Surname_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Surname_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Telephone_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Telephone_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''email_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents email_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Password_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Password_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ConfirmPassword_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConfirmPassword_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Status_Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Status_Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Return_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Return_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Register_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Register_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Delete_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Delete_Button As Global.System.Web.UI.WebControls.Button
End Class
