'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MasterPage

    '''<summary>
    '''head control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents head As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''Menu_Div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Menu_Div As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Home control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Home As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''Menu_Home control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Menu_Home As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SubMenu_Home_Div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubMenu_Home_Div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SubMenu_Home_Table control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubMenu_Home_Table As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Competitions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Competitions As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''Menu_Competitions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Menu_Competitions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SubMenu_Competitions_Div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubMenu_Competitions_Div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SubMenu_Competitions_Table control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubMenu_Competitions_Table As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''League control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents League As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''Menu_League control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Menu_League As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SubMenu_League_Div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubMenu_League_Div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SubMenu_League_Table control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubMenu_League_Table As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''HBSA_menu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HBSA_menu As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''Menu_HBSA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Menu_HBSA As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SubMenu_HBSA_Div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubMenu_HBSA_Div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SubMenu_HBSA_Table control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubMenu_HBSA_Table As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Menu_ROH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Menu_ROH As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SubMenu_ROH_Div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubMenu_ROH_Div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SubMenu_ROH_Table control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubMenu_ROH_Table As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''HandbookMenuItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HandbookMenuItem As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Contact_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Contact_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ClubLogin_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClubLogin_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Login_button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Login_button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Covid_19_Compliance_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Covid_19_Compliance_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''MatchResult_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MatchResult_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''EntryForm_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EntryForm_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''MyProfile_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MyProfile_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Fines_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fines_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Admin_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Admin_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ClubLogin_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClubLogin_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Login_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Login_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Premium_Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Premium_Image As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''adLink5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adLink5 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''adImage5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adImage5 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''adLink6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adLink6 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''adImage6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adImage6 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''ContentPlaceHolder1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentPlaceHolder1 As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''adLink2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adLink2 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''adImage2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adImage2 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''adLink3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adLink3 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''adImage3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adImage3 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''adLink4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adLink4 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''adImage4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adImage4 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''SiteMap_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SiteMap_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''HitCount_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HitCount_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Page_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Page_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Version_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Version_Literal As Global.System.Web.UI.WebControls.Literal
End Class
