'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MatchResult

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''loadingDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loadingDiv As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''SessionUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessionUser As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''SessionEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessionEmail As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''SessionPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessionPassword As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''SessionUserID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessionUserID As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''SessionUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessionUserName As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''SessionAdminEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessionAdminEmail As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''SessionTeamID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessionTeamID As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''SessionAwayTeamID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessionAwayTeamID As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''SessionMatchResultID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessionMatchResultID As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''Home_Player_IDs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Home_Player_IDs As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''Away_Player_IDs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Away_Player_IDs As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''status_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents status_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CardDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CardDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''League_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents League_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Section_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Section_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''FixtureDate_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FixtureDate_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''matchDate_Textbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents matchDate_Textbox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''matchDate_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents matchDate_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''HomeTeam_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''AwayTeam_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''HomeHcap1_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeHcap1_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HomeHCapImg1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeHCapImg1 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''HomeScore1_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore1_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HomePlayer1_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomePlayer1_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''AwayPlayer1_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayPlayer1_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''AwayHcap1_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayHcap1_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AwayHCapImg1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayHCapImg1 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''AwayScore1_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore1_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HomeHcap2_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeHcap2_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HomeHCapImg2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeHCapImg2 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''HomeScore2_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore2_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HomePlayer2_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomePlayer2_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''AwayPlayer2_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayPlayer2_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''AwayHcap2_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayHcap2_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AwayHCapImg2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayHCapImg2 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''AwayScore2_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore2_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HomeHcap3_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeHcap3_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HomeHCapImg3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeHCapImg3 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''HomeScore3_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore3_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HomePlayer3_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomePlayer3_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''AwayPlayer3_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayPlayer3_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''AwayHcap3_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayHcap3_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AwayHCapImg3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayHCapImg3 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''AwayScore3_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore3_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HomeHcap4_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeHcap4_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HomeHCapImg4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeHCapImg4 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''HomeScore4_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore4_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HomePlayer4_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomePlayer4_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''AwayPlayer4_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayPlayer4_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''AwayHcap4_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayHcap4_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AwayHCapImg4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayHCapImg4 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''AwayScore4_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore4_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''webPage_HomeBreaks_Table control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents webPage_HomeBreaks_Table As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''HomeBreakPlayers_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeBreakPlayers_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''HomeBreak_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeBreak_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''webPage_AwayBreaks_Table control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents webPage_AwayBreaks_Table As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''AwayBreakPlayers_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayBreakPlayers_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''AwayBreak_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayBreak_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HomeFrames_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeFrames_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''AwayFrames_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayFrames_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Send_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Send_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Retry_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Retry_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Cancel_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cancel_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Recover_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Recover_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Delete_Result_Div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Delete_Result_Div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DeleteResult_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteResult_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Remove_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Remove_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Cancel_Delete_Result_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cancel_Delete_Result_Button As Global.System.Web.UI.HtmlControls.HtmlInputButton
End Class
