'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PayPalConfirm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''Update_Progress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Update_Progress As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''CompetitionsPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompetitionsPanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Club_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Club_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Confirm_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Confirm_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''PaymentID_Literal1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaymentID_Literal1 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Amount_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Amount_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Note_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Note_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Confirm_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Confirm_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Paid_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Paid_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Paid_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Paid_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''FullAmount_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FullAmount_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Outstanding_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Outstanding_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''PaymentID_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaymentID_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''TransactionID_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionID_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''print_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents print_Button As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''Payments_gridview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Payments_gridview As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''TodaysDate_Receipt_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TodaysDate_Receipt_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''PaidBy_Receipt_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaidBy_Receipt_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ClubName_Receipt_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClubName_Receipt_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Amount_Receipt_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Amount_Receipt_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''PaymentID_Receipt_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaymentID_Receipt_Literal As Global.System.Web.UI.WebControls.Literal
End Class
