'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PictureGallery

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''Room_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Room_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Text_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Text_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Thumbnails_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Thumbnails_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''PictureIndex_Hidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PictureIndex_Hidden As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''PicturesCount_Hidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PicturesCount_Hidden As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''firstButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents firstButton As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''prevButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents prevButton As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''exitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents exitButton As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''nextButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nextButton As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''lastButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lastButton As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''ImageDescription_Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageDescription_Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Picture_Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Picture_Image As Global.System.Web.UI.WebControls.Image
End Class
