'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Contact1

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''Update_Progress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Update_Progress As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Contact_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Contact_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Destination_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Destination_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''name_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents name_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Email_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Email_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Phone_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Phone_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CompsRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompsRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Competitions_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Competitions_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''HcapRow7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HcapRow7 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Justify_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Justify_CheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''HcapRow1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HcapRow1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Player_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Player_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HcapRow6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HcapRow6 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''PlayerPhone_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlayerPhone_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HcapRow2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HcapRow2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''League_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents League_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Clubs_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Clubs_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''HcapRow3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HcapRow3 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Team_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''HcapRow4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HcapRow4 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Handicap_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Handicap_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HcapRow5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HcapRow5 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Reasons_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Reasons_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''body_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents body_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''captcha_Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents captcha_Image As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''captcha_Textbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents captcha_Textbox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''captchaRefresh_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents captchaRefresh_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Copy_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Copy_CheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Send_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Send_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''status_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents status_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''MessageSent_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MessageSent_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''MessageSent_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MessageSent_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Home_HyperLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Home_HyperLink As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Contact_HyperLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Contact_HyperLink As Global.System.Web.UI.WebControls.HyperLink
End Class
