'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LogIn1
    
    '''<summary>
    '''status_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents status_Literal As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''Request_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Request_Panel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Request_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Request_Literal As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''Instruction_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Instruction_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''RequestEmail_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequestEmail_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequestPasswordHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequestPasswordHeader As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''RequestPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequestPassword As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''RequestPassword_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequestPassword_TextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RequestTeamHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequestTeamHeader As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''RequestTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequestTeam As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''RequestTeam_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequestTeam_DropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''SubmitRequest_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitRequest_Button As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''CancelRequest_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelRequest_Button As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Login_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Login_Panel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''email_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents email_TextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''password_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents password_TextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Login_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Login_Button As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Password_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Password_Button As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Profile_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Profile_Button As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Register_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Register_Button As Global.System.Web.UI.WebControls.Button
End Class
