'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MatchResult1

    '''<summary>
    '''MatchDetails_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MatchDetails_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Frame_Literal1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Frame_Literal1 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Frame_Literal2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Frame_Literal2 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Frame_Literal3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Frame_Literal3 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Frame_Literal4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Frame_Literal4 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''MatchBreaks_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MatchBreaks_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Result_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Result_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''PanelsDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelsDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Match_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Match_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Section_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Section_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''HomeTeam_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''FixtureDate_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FixtureDate_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Fixture_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fixture_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''AwayTeam_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam_Literal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''matchDate_Textbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents matchDate_Textbox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Next_Button0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Next_Button0 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Frame1_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Frame1_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''HomePlayer1_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomePlayer1_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''HomeHcap1_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeHcap1_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HomeHCapImg1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeHCapImg1 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''HomeScore1_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore1_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AwayPlayer1_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayPlayer1_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''AwayHcap1_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayHcap1_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AwayHCapImg1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayHCapImg1 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''AwayScore1_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore1_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Prev_Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Prev_Button1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Next_Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Next_Button1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Frame2_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Frame2_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''HomePlayer2_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomePlayer2_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''HomeHcap2_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeHcap2_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HomeHCapImg2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeHCapImg2 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''HomeScore2_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore2_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AwayPlayer2_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayPlayer2_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''AwayHcap2_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayHcap2_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AwayHCapImg2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayHCapImg2 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''AwayScore2_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore2_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Prev_Button2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Prev_Button2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Next_Button2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Next_Button2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Frame3_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Frame3_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''HomePlayer3_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomePlayer3_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''HomeHcap3_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeHcap3_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HomeHCapImg3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeHCapImg3 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''HomeScore3_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore3_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AwayPlayer3_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayPlayer3_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''AwayHcap3_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayHcap3_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AwayHCapImg3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayHCapImg3 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''AwayScore3_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore3_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Prev_Button3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Prev_Button3 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Next_Button3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Next_Button3 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Frame4_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Frame4_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''HomePlayer4_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomePlayer4_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''HomeHcap4_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeHcap4_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HomeHCapImg4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeHCapImg4 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''HomeScore4_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore4_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AwayPlayer4_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayPlayer4_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''AwayHcap4_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayHcap4_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AwayHCapImg4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayHCapImg4 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''AwayScore4_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore4_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Prev_Button4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Prev_Button4 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Next_Button4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Next_Button4 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Breaks_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Breaks_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Breaks_GridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Breaks_GridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''BreakPlayers_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BreakPlayers_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Break_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Break_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BreakAdd_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BreakAdd_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''breakErrorRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents breakErrorRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Breaks_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Breaks_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Prev_Button5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Prev_Button5 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Next_Button5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Next_Button5 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''SubmitResult_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitResult_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Prev_Button6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Prev_Button6 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''status_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents status_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Send_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Send_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Cancel_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cancel_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Retry_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Retry_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Recover_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Recover_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Delete_Result_Div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Delete_Result_Div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SessionUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessionUser As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''SessionEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessionEmail As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''SessionPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessionPassword As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''SessionUserID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessionUserID As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''SessionUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessionUserName As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''SessionadminDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessionadminDetails As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''SessionTeamID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessionTeamID As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''SessionAwayTeamID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessionAwayTeamID As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''SessionMatchResultID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessionMatchResultID As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HomeFrames control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeFrames As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''AwayFrames control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayFrames As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''SessionBreaksTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessionBreaksTable As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''DeleteResult_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteResult_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Remove_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Remove_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Cancel_Delete_Result_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cancel_Delete_Result_Button As Global.System.Web.UI.HtmlControls.HtmlInputButton
End Class
