'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MobileMaster

    '''<summary>
    '''head control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents head As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''Premium_Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Premium_Image As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''NonMobile_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NonMobile_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Login_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Login_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''clubLogin_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clubLogin_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''AccessCode_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AccessCode_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''AccessCode_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AccessCode_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AccessCode_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AccessCode_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''leftMenu_Div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents leftMenu_Div As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Home control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Home As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''Menu_Home control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Menu_Home As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SubMenu_Home_Div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubMenu_Home_Div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SubMenu_Home_Table control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubMenu_Home_Table As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Meetings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Meetings As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''Menu_Meetings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Menu_Meetings As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SubMenu_Meetings_Div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubMenu_Meetings_Div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SubMenu_Meetings_Table control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubMenu_Meetings_Table As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Competitions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Competitions As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''Menu_Competitions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Menu_Competitions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SubMenu_Competitions_Table control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubMenu_Competitions_Table As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''League control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents League As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''Menu_League control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Menu_League As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SubMenu_League_Table control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubMenu_League_Table As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''HBSA_menu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HBSA_menu As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''Menu_HBSA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Menu_HBSA As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SubMenu_HBSA_Div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubMenu_HBSA_Div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SubMenu_HBSA_Table control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubMenu_HBSA_Table As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Menu_ROH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Menu_ROH As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SubMenu_ROH_Div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubMenu_ROH_Div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SubMenu_ROH_Table control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubMenu_ROH_Table As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''HandbookMenuItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HandbookMenuItem As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''rightMenu_Div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rightMenu_Div As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''contactUsButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents contactUsButton As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''contactUsRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents contactUsRef As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''clubLoginButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clubLoginButton As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''clubLoginRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clubLoginRef As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''teamLoginButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents teamLoginButton As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''Login_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Login_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''AGMVoteButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AGMVoteButton As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''AGMVoteRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AGMVoteRef As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Covid19Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Covid19Button As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''resultButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents resultButton As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''EntryFormButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EntryFormButton As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''myRegistrationButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents myRegistrationButton As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''finesButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents finesButton As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''helpFAQButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents helpFAQButton As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''advertDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents advertDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''advertURL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents advertURL As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''adImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adImage As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''ContentPlaceHolder1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentPlaceHolder1 As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''Footer_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Footer_Literal As Global.System.Web.UI.WebControls.Literal
End Class
