'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Adverts

    '''<summary>
    '''Add_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Add_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Adverts_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Adverts_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''actionButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents actionButtons As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''Change_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Change_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Delete_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Delete_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Download_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Download_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Message_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Message_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''UpLoad_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpLoad_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UploadFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UploadFile As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''Advertiser_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Advertiser_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''WebURL_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WebURL_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpLoad_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpLoad_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Download_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Download_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Advertiser_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Advertiser_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''snapshot_img control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents snapshot_img As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''Files_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Files_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Delete_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Delete_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''DeletePanel_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeletePanel_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Delete_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Delete_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ConfirmDelete_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConfirmDelete_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Cancel_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cancel_Button As Global.System.Web.UI.WebControls.Button
End Class
