'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Awards

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Report_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Report_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Generate_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Generate_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ExportCells control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExportCells As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Export_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Export_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''AddWinner_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddWinner_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Status_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Status_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Awards_GridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Awards_GridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Edit_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Edit_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''EditPanel_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditPanel_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''EditPanel_Literal2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditPanel_Literal2 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''EditStatus_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditStatus_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''AwardType_HiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwardType_HiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''AwardID_HiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwardID_HiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''SubID_HiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubID_HiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''LeagueID_HiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LeagueID_HiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''EntrantID_HiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EntrantID_HiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Entrant2ID_HiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Entrant2ID_HiddenField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''AvailableAwards_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AvailableAwards_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LeagueCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LeagueCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''CompetitionCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompetitionCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TrophyCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrophyCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''WinnerCell_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WinnerCell_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AutoCompleteExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AutoCompleteExtender1 As Global.AjaxControlToolkit.AutoCompleteExtender

    '''<summary>
    '''TextBoxWatermarkExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxWatermarkExtender1 As Global.AjaxControlToolkit.TextBoxWatermarkExtender

    '''<summary>
    '''AwardCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwardCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''Submit_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Submit_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Cancel_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cancel_Button As Global.System.Web.UI.WebControls.Button
End Class
