'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BetweenSeasons
    
    '''<summary>
    '''Introduction_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Introduction_Panel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Err_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Err_Literal As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''CloseSeason_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CloseSeason_Button As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Handicaps_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Handicaps_Button As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Player_Tags_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Player_Tags_Button As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''SetupEntryForms_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SetupEntryForms_Button As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''EntryForms_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EntryForms_Button As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Start_Season_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Start_Season_Button As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Season_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Season_Panel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Season_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Season_Literal As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''Confirm_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Confirm_Button As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Cancel_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cancel_Button As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Handicaps_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Handicaps_Panel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Section_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Section_DropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Close_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Close_Button As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Update_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Update_Button As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Teams_GridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Teams_GridView As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''Confirm_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Confirm_Panel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Confirm_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Confirm_Literal As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ConfirmApply_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConfirmApply_Button As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ApplyTags_Cancel_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ApplyTags_Cancel_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ClubsWithoutPrivacyAccepted_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClubsWithoutPrivacyAccepted_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ClubsWithoutPrivacyAccepted_GridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClubsWithoutPrivacyAccepted_GridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ClubsWithoutPrivacyAccepted_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClubsWithoutPrivacyAccepted_Button As Global.System.Web.UI.WebControls.Button
End Class
