'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ClearCompetitionsEntryForms
    
    '''<summary>
    '''ClearCompsEntryForms_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClearCompsEntryForms_Literal As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ClearCompsEntryForms_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClearCompsEntryForms_Button As Global.System.Web.UI.WebControls.Button
End Class
