'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CompetitionsEntries

    '''<summary>
    '''ToolkitScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolkitScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''MainPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainPage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ApplyEntryForms_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ApplyEntryForms_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Competitions_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Competitions_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SelectCompetition_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectCompetition_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''MakeDraw_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MakeDraw_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Status_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Status_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''AddEntry_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddEntry_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Entrants_GridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Entrants_GridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Juniors_SetUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Juniors_SetUp As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''JuniorsMiniLeagues_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JuniorsMiniLeagues_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Juniors_SetUp_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Juniors_SetUp_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Juniors_SetUp_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Juniors_SetUp_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Replace_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Replace_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Add_Table control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Add_Table As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''ClearDraw_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClearDraw_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CancelAddEntry_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelAddEntry_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Replace_Table control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Replace_Table As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Entrants_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Entrants_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Entrant2_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Entrant2_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Entrant2_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Entrant2_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Entrant_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Entrant_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AutoCompleteExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AutoCompleteExtender1 As Global.AjaxControlToolkit.AutoCompleteExtender

    '''<summary>
    '''Entrant2_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Entrant2_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AutoCompleteExtender2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AutoCompleteExtender2 As Global.AjaxControlToolkit.AutoCompleteExtender

    '''<summary>
    '''ReplaceStatus_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReplaceStatus_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Literal1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Literal1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Submit_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Submit_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Literal2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Literal2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CancelReplace_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelReplace_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Confirm_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Confirm_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Confirm_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Confirm_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ConfirmCompetition_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConfirmCompetition_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CancelConfirm_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelConfirm_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ClubsWithoutPrivacyAccepted_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClubsWithoutPrivacyAccepted_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ClubsWithoutPrivacyAccepted_GridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClubsWithoutPrivacyAccepted_GridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ClubsWithoutPrivacyAccepted_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClubsWithoutPrivacyAccepted_Button As Global.System.Web.UI.WebControls.Button
End Class
