'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DocumentManager

    '''<summary>
    '''Documents_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Documents_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''NewDocument_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewDocument_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpLoad_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpLoad_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''DownloadTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DownloadTable As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''downLoadRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents downLoadRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Download_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Download_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Delete_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Delete_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''removeDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents removeDoc As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Remove_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Remove_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Confirm_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Confirm_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Cancel_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cancel_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''FileUploadControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUploadControl As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''UpLoad_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpLoad_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Status_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Status_Literal As Global.System.Web.UI.WebControls.Literal
End Class
