'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FixtureDates

    '''<summary>
    '''ScriptManager2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager2 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''UpdateProgress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgress1 As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Section_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Section_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Main_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Main_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''StartDate_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StartDate_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''StartDate_Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StartDate_Image As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''StartDate_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StartDate_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''CurfewStart_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CurfewStart_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CurfewStart_Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CurfewStart_Image As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''CurfewStart_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CurfewStart_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''CurfewEnd_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CurfewEnd_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CurfewEnd_Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CurfewEnd_Image As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''CurfewEnd_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CurfewEnd_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''NumberOfFixtures_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NumberOfFixtures_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Recalc_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Recalc_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Err_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Err_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''FixtureDates_GridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FixtureDates_GridView As Global.System.Web.UI.WebControls.GridView
End Class
