'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Players

    '''<summary>
    '''ToolkitScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolkitScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''Update_Progress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Update_Progress As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''SessionUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessionUser As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''LeagueSection_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LeagueSection_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Club_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Club_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''GetByClub_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GetByClub_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Player_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Player_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AutoCompleteExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AutoCompleteExtender1 As Global.AjaxControlToolkit.AutoCompleteExtender

    '''<summary>
    '''GetByName_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GetByName_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Add_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Add_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''help_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents help_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Edit_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Edit_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''EditPanel_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditPanel_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Status_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Status_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''PlayerID_Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlayerID_Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Controls_Table control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Controls_Table As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''editLeague_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents editLeague_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''editClubs_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents editClubs_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Team_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''editSection_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents editSection_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ErrorTeamRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ErrorTeamRow As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''ErrorTeam_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ErrorTeam_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Forename_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Forename_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Inits_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Inits_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Surname_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Surname_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Handicap_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Handicap_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''email_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents email_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TelNo_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TelNo_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Played_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Played_CheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Tagged_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tagged_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Over70_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Over70_CheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''SubmitPlayer_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitPlayer_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CancelPlayer_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelPlayer_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Players_GridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Players_GridView As Global.System.Web.UI.WebControls.GridView
End Class
