'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Sections

    '''<summary>
    '''Add_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Add_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Err_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Err_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Sections_GridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Sections_GridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Edit_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Edit_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''EditPanel_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditPanel_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Edit_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Edit_Literal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ID_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ID_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SectionName_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SectionName_TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''League_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents League_DropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ReversedMatrix_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReversedMatrix_CheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''AssignMatrix_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AssignMatrix_CheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''SubmitPlayer_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitPlayer_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CancelPlayer_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelPlayer_Button As Global.System.Web.UI.WebControls.Button
End Class
