'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UserDetails
    
    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''Type_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Type_DropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Clubs_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Clubs_DropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Confirmed_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Confirmed_DropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''GetReport_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GetReport_Button As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''NewUser_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewUser_Button As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Team_Row control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team_Row As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''Leagues_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Leagues_DropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Team_DropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team_DropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Users_GridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Users_GridView As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''Edit_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Edit_Panel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''EditPanel_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditPanel_Literal As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''Password_Hidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Password_Hidden As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''UserID_Hidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserID_Hidden As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''EditType_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditType_Literal As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''Status_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Status_Literal As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''EditClubTeamHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditClubTeamHeader As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''EditEmail_Textbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditEmail_Textbox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''editPassword_textbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents editPassword_textbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''editClubTeam_DropdownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents editClubTeam_DropdownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''editConfirmed_CheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents editConfirmed_CheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''editForename_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents editForename_TextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''editSurname_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents editSurname_TextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''editTelephone_Textbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents editTelephone_Textbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''editUser_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents editUser_Button As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''CancelEdit_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelEdit_Button As Global.System.Web.UI.WebControls.Button
End Class
